### ISSUE TITLE
Can't download TWL.jar

### ISSUE THREAD

**Issue by shaktithakran** [multi-io/VolKit#1]
The website http://twl.l33tlabs.org/ seems to be down. Can you provide a working version of this file?

**Comment by multi-io** [comment]
Here is mine. I've had to rename it to TWL.zip to be able to upload it here (github won't accept .jars). MD5 is 63838a87b455eb10d38c26e197c7ec47. Just rename it back and copy it into tmp/. 
[TWL.zip](https://github.com/multi-io/VolKit/files/281905/TWL.zip)

**Comment by indiego** [comment]
Haven't made any changes to your code and it gives me this. Will look into it later myself.

`Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: org.lwjgl.DefaultSysImplementation.getPointerSize()I
    at org.lwjgl.DefaultSysImplementation.getPointerSize(Native Method)
    at org.lwjgl.Sys.<clinit>(Sys.java:113)
    at org.lwjgl.opengl.AWTGLCanvas.<clinit>(AWTGLCanvas.java:87)
    at de.olafklischat.volkit.App.<init>(App.java:75)
    at de.olafklischat.volkit.App$1.run(App.java:60)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
`
